#!/usr/bin/bash

echo 'please wait while we prep the environment (should take about 10 seconds)'

cat <<EOF > emc-ddl.sql
-- Client table
CREATE TABLE client (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first VARCHAR(50) NOT NULL,
	last VARCHAR(50),
	email VARCHAR(80) NOT NULL,
  career_interests TEXT[] NOT NULL
);

-- Event table
CREATE TYPE event_mode AS ENUM ('Virtual', 'In-person');

CREATE TABLE event (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  event_dt tstzrange NOT NULL,
  mode event_mode NOT NULL
);

-- Attendance table
CREATE TABLE attendance (
  event_id INTEGER REFERENCES event(id),
  client_id INTEGER REFERENCES client(id),
  attend_status TEXT NOT NULL CHECK (attend_status in ('Registered', 'Attended', 'Canceled', 'No Show'))
    DEFAULT 'Registered',
  PRIMARY KEY (event_id, client_id)
);

-- Payment table
CREATE TABLE payment (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date timestamptz NOT NULL,
    type TEXT NOT NULL 
        CHECK (type in ('Event', 'Package')),    
    status TEXT 
        CHECK (status in ('Waive', 'Refund')), 
    client_id INTEGER REFERENCES client(id),
    event_id INTEGER REFERENCES event(id),
    amount NUMERIC(8,2) NOT NULL,
    balance NUMERIC(8,2) NOT NULL
);

EOF

cat <<EOF > emc-data.sql
-- Add Clients
INSERT INTO client (first, last, email, career_interests) 
  VALUES ('Wilhelmina', 'Wybrow', 'wwybrow0@elegantthemes.com', '{"Programming", "Project Management", "Web Development"}'),
        ('Domenic', 'Perotti', 'dperotti2@blog.com', '{"Athletic coaching", "personal training"}'),
        ('Mart', 'Wellbelove', 'mwellbelove3@ibm.com', '{"Product Management", "UX"}'),
        ('Ricky', 'MacGillivray', 'rmacgillivray4@eepurl.com', '{"Counseling", "Personal Coaching", "Community Management"}'),
        ('Nina', 'Ferrand', 'nferrand5@lycos.com', '{"Music", "Audio engineering", "Radio", "Film Production", "Screenwriting"}')
;

-- Add Events
INSERT INTO event (name, event_dt, mode)
  VALUES ('Individual Appointment', '[2019-12-02 14:30 PST, 2019-12-02 15:30 PST)', 'In-person'),
        ('Individual Appointment', '[2019-12-11 17:00 EST, 2019-12-11 17:30 EST)', 'Virtual'),
        ('Resume and Cover Letter Workshop', '[2019-12-14 10:00 PST, 2019-12-14 12:00 PST)', 'In-person'),
        ('Interview Practice', '[2020-01-11 09:00 PST, 2020-01-11 12:00 PST)', 'In-person')
;

-- Add Payments
INSERT INTO payment (date, type, client_id, event_id, amount, balance)
  VALUES ('2020-01-10 13:00 PST',
        'Event',
        1,
        4,
        20.00,
        0.00)
;

EOF

echo 'starting the database'
docker network create mybridge

docker run -d --network mybridge -p 5432:5432 -e PG_USER=groot -e PG_PASSWORD=password -e PG_DATABASE=workshop --name=pgsql crunchydata/crunchy-postgres-appdev:latest

until PGPASSWORD="password" psql -h localhost -U groot postgres -c '\l' &> /dev/null; do
  echo >&2 "$(date +%Y%m%dt%H%M%S) Waiting for Postgres to start"
  sleep 1
done

until PGPASSWORD="password" psql -h localhost -U groot -f emc-ddl.sql workshop &> /dev/null; do
  echo >&2 "$(date +%Y%m%dt%H%M%S) loading employee schema"
  sleep 1
done

until PGPASSWORD="password" psql -h localhost -U groot -f emc-data.sql workshop &> /dev/null; do
  echo >&2 "$(date +%Y%m%dt%H%M%S) loading employees data"
  sleep 1
done

echo 'finished loading  data'

clear

: 'ready to go!'

PGPASSWORD="password" psql -h localhost -U groot workshop

